name: Terraform

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project Folder"
        required: true
        default: "landing-zone"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: projects/${{ github.event.inputs.project }}
        run: terraform init

      - name: Terraform Validate
        working-directory: projects/${{ github.event.inputs.project }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: projects/${{ github.event.inputs.project }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: projects/${{ github.event.inputs.project }}
        run: terraform apply -auto-approve tfplan